site_name: Meowtopia

nav:
  - 首页: index.md
  # 基础知识
  - 日常护理:
    - 新手入门: blog/care/beginner-guide.md
    - 清洁护理: blog/care/grooming.md
    - 室内养护: blog/care/indoor-care.md
  - 营养喂食:
    - 喂食指南: blog/nutrition/food-guide.md
    - 营养建议: blog/nutrition/diet-tips.md
  - 行为解读:
    - 身体语言: blog/behavior/body-language.md
    - 行为训练: blog/behavior/training.md
  # 进阶内容
  - 医疗健康:
    - 常见疾病: blog/health/common-disease.md
    - 疫苗接种: blog/health/vaccination.md
    - 医疗资源: blog/health/medical-resources.md
  - 急救知识:
    - 基础急救: blog/emergency/first-aid.md
    - 案例分享: blog/emergency/cases.md
  - 行为训练:
    - 如厕训练: blog/training/toilet.md
    - 互动游戏: blog/training/play.md
    - 行为纠正: blog/training/correction.md
  - 流浪救助:
    - 救助指南: blog/rescue/guide.md
    - 救助站点: blog/rescue/stations.md
    - TNR实践: blog/rescue/tnr.md
    - 领养须知: blog/rescue/adoption.md
  # 推荐资源
  - 优质网站:
    - 行为训练: blog/websites/behavior.md
    - 社区论坛: blog/websites/community.md
    - 医疗健康: blog/websites/medical.md
    - 营养知识: blog/websites/nutrition.md
    - 购物导航: blog/websites/shopping.md
  - 推荐视频:
    - 行为训练: blog/videos/behavior.md
    - 品种介绍: blog/videos/breeds.md
    - 日常护理: blog/videos/care.md
    - 娱乐视频: blog/videos/entertainment.md
    - 环境布置: blog/videos/environment.md
    - 食品营养: blog/videos/food.md
    - 美容护理: blog/videos/grooming.md
    - 医疗相关: blog/videos/medical.md
    - 营养饮食: blog/videos/nutrition.md
    - 救助相关: blog/videos/rescue.md
    - 训练教育: blog/videos/training.md
  - 推荐书籍:
    - 新手入门: blog/books/beginner.md
    - 猫咪心理: blog/books/psychology.md
    - 医疗健康: blog/books/medical.md
    - 训练教育: blog/books/training.md
    - 营养饮食: blog/books/nutrition.md
  - 实用工具:
    - 美容工具: blog/tools/grooming.md
    - 医疗用品: blog/tools/medical.md
    - 喂食工具: blog/tools/feeding.md
    - 清洁用品: blog/tools/cleaning.md
    - 玩具用品: blog/tools/toys.md
  - 经验分享:
    - 养猫心得: blog/experience/tips.md
    - 案例分析: blog/experience/cases.md
    - 经验总结: blog/experience/summary.md
  - 关于我们: about.md

theme:
  language: 'zh'
  name: material
  icon:
    repo: fontawesome/brands/git-alt  # Font Awesome 的 Git Alt 图标
  palette:
      - scheme: default  # 明亮模式配色
        primary: "#87ceeb"   # 天空蓝主色
        accent: "#f7a8b8"    # 樱花粉辅助色
        toggle:
          icon: material/weather-sunny
          name: 切换到暗模式
      - scheme: slate    # 暗模式配色
        primary: deep purple  # 深紫色主色
        accent: deep purple   # 使用相同的深紫色作为辅助色
        toggle:
          icon: material/weather-night
          name: 切换到明亮模式
  font:
    text: Noto Sans SC, Roboto
    code: Source Code Pro
  features:
    - navigation.tabs
    - navigation.sections
    # - navigation.tabs.sticky  # 固定标签导航栏
    - navigation.top       # 返回顶部按钮
    - navigation.tracking  # 在 URL 中跟踪当前位置
    - navigation.footer     # 显示上一页/下一页导航
    - navigation.indexes    # 支持章节索引页面
    - navigation.instant  # 即时加载页面
    - navigation.instant.prefetch  # 预加载链接页面
    - navigation.instant.progress  # 显示加载进度条
    - navigation.prune    # 修剪导航树
    # - header.autohide
    - search.highlight
    - search.share
    - search.suggest
    - announce.dismiss
    - toc.follow         # 目录跟随滚动
    - toc.numbered
    - content.code.copy
  announce: false
  logo: assets/favicon.svg
  custom_dir: overrides




plugins:
  - search:
      lang:
        - en
        - zh
  - macros
  - tags

markdown_extensions:
  - meta   # 支持文章元数据
  - toc:    # 支持目录
      permalink: true  # 为标题添加永久链接
      toc_depth: 3   # 目录深度，显示到 h3
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight    # 代码高亮

extra:
  social:
    # - icon: fontawesome/brands/github-alt
    - icon: fontawesome/brands/github
      link: https://github.com/FreemanKevin
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/freelabspace/meowtopia
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/freemankevin.bsky.social
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@freemankevin
  favicon: assets/images/favicon.png
  extra_css:
    - styles/fonts.css
    - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js



# 网站描述
site_description: Meowtopia is a comprehensive blog dedicated to all things related to cats. Here, you'll find a wealth of information covering cat care, behavior, health, nutrition, and much more. Whether you're a new cat owner or a seasoned feline enthusiast, Meowtopia offers valuable insights, tips, and engaging content to help you better understand and care for your furry friends.
# 作者信息
site_author: Freeman Kevin
# 网站链接
site_url: https://meowtopia.uk/
# 版权信息
copyright: "Copyright © 2016 - 2025 Meowtopia"

# 添加 GitHub 仓库信息
repo_url: https://github.com/FreemanKevin/Meowtopia
repo_name: FreemanKevin/Meowtopia
