site_name: Meowtopia
# GitHub库的名称
repo_name: 'Meowtopia'
# GitHub库的链接
repo_url: 'https://github.com/FreemanKevin/Meowtopia'

nav:
  - 首页: 
    - 欢迎: index.md
  - 日常护理:
    - 概述: blog/care/index.md
    - 清洁护理: blog/care/grooming.md
    - 室内养护: blog/care/indoor-care.md
  - 医疗健康:
    - 概述: blog/health/index.md
    - 常见疾病: blog/health/common-disease.md
    - 疫苗接种: blog/health/vaccination.md
  - 行为解读:
    - 概述: blog/behavior/index.md
    - 身体语言: blog/behavior/body-language.md
    - 行为训练: blog/behavior/training.md
  - 营养喂食:
    - 概述: blog/nutrition/index.md
    - 喂食指南: blog/nutrition/food-guide.md
    - 营养建议: blog/nutrition/diet-tips.md
  - 急救知识:
    - 概述: blog/emergency/index.md
    - 基础急救: blog/emergency/first-aid.md
    - 案例分享: blog/emergency/cases.md
  - 优质资源:
    - 概述: blog/resources/index.md
    - YouTube推荐: blog/resources/youtube.md
    - 书籍推荐: blog/resources/books.md
  - 关于: about.md




theme:
  language: 'zh'
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
      - scheme: default
        primary: teal
        accent: amber
        toggle:
          icon: material/toggle-switch-off-outline
          name: 切换到暗模式
      - scheme: slate
        primary: deep purple
        accent: light blue
        toggle:
          icon: material/toggle-switch
          name: 切换到明亮模式
  font:
    text: "Noto Serif SC, serif"
    code: "Source Code Pro, DM Mono, Noto Serif SC, monospace"
  features:
    - navigation.tabs        # 启用顶部导航标签
    - navigation.tabs.sticky # 使导航标签在滚动时保持可见
    - navigation.sections    # 使用分段显示导航
    - navigation.top        # 添加返回顶部按钮
    - header.autohide
    - palette-toggle
  logo: assets/favicon.svg
  




plugins:
  - search:
      lang:
        - en
        - zh
  - macros
  - blog:
      blog_dir: blog
      post_date_format: yyyy-MM-dd
      post_url_format: "{date}/{slug}"
  - tags  # 支持文章标签
  - rss:
      abstract_chars_count: 160
      date_from_meta:
        as_creation: date
      enabled: true
      feed_ttl: 1440
      length: 20

markdown_extensions:
  - meta   # 支持文章元数据
  - toc    # 支持目录
  - pymdownx.highlight    # 代码高亮
  - pymdownx.superfences  # 支持代码块

extra:
  social:
    - icon: fontawesome/brands/github-alt  # 使用 Font Awesome 的 GitHub 图标
      link: https://github.com/FreemanKevin
    - icon: fontawesome/brands/bluesky  # BlueSky 官方图标
      link: https://bsky.app/profile/freemankevin.bsky.social
    - icon: fontawesome/brands/mastodon  # Mastodon 官方图标
      link: https://mastodon.social/@freemankevin
  favicon: assets/images/favicon.png
  extra_css:
    - styles/fonts.css  # 确保文件存在



# 网站名称
site_name: Meowtopia
# 网站描述
site_description: Meowtopia is a comprehensive blog dedicated to all things related to cats. Here, you'll find a wealth of information covering cat care, behavior, health, nutrition, and much more. Whether you're a new cat owner or a seasoned feline enthusiast, Meowtopia offers valuable insights, tips, and engaging content to help you better understand and care for your furry friends.
# 作者信息
site_author: Freeman Kevin
# 网站链接
site_url: https://meowtopia.uk/
# 版权信息
copyright: "© 2025 Freeman Kevin"
