name: build
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 16 * * *'  # 每天UTC 16:00 (北京时间凌晨0:00)
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.11

permissions:
  contents: read

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python runtime
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Set up Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build documentation
        run: mkdocs build

  docker:
    runs-on: ubuntu-latest
    needs: python
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate Docker tags and labels
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            freelabspace/meowtopia
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=short
            type=ref,event=branch
            type=ref,event=pr
          labels: |
            org.opencontainers.image.title=Meowtopia
            org.opencontainers.image.description=A comprehensive cat care documentation site
            org.opencontainers.image.source=https://github.com/FreemanKevin/Meowtopia

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=freelabspace/meowtopia:buildcache
          cache-to: type=registry,ref=freelabspace/meowtopia:buildcache,mode=max

      - name: Check Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker pull freelabspace/meowtopia:latest
          docker image inspect freelabspace/meowtopia:latest 